#file docker-compose.yml 
version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - web
    depends_on:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - web
networks:
  web:
